"""Generate the repository CI workflow from immutable toolchain action pins."""
import argparse
import json
from pathlib import Path
import tempfile

ROOT=Path(__file__).resolve().parents[1]
TEMPLATE='''# Generated by python tools/sync_ci.py; pins belong to build/toolchain.lock.json.
name: Verify
on:
  push:
    branches: [develop, 'codex/**']
  pull_request:
    branches: [develop]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@CHECKOUT_PIN
        with:
          persist-credentials: false
      - name: Install pinned build driver
        run: |
          python3 -m venv work/ci-runtime
          work/ci-runtime/bin/python -m pip install uv==UV_PIN
          echo "$PWD/work/ci-runtime/bin" >> "$GITHUB_PATH"
      - name: Check generated inputs
        run: |
          python3 tools/sync_ci.py --check
          python3 tools/sync_toolchain.py --check
      - name: Empty setup and offline source tests
        run: |
          set -o pipefail
          python3 tools/dev.py --instance ci setup --port 8000 2>&1 | tee work/ci-setup.txt
          python3 tools/dev.py --instance ci test 2>&1 | tee work/ci-tests.txt
      - name: Compare isolated release builds and installed artifacts
        run: python3 tools/repro_build.py
      - uses: actions/upload-artifact@UPLOAD_PIN
        if: always()
        with:
          name: verification-evidence
          path: |
            work/ci-setup.txt
            work/ci-tests.txt
            work/repro-build/*/*/*.whl
          if-no-files-found: error
          retention-days: 14
'''


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');args=p.parse_args()
    pins=json.loads((ROOT/'build/toolchain.lock.json').read_text())
    content=TEMPLATE.replace('CHECKOUT_PIN',pins['ci_actions']['checkout']).replace('UPLOAD_PIN',pins['ci_actions']['upload_artifact']).replace('UV_PIN',pins['uv_version'])
    target=ROOT/'.github/workflows/verify.yml'
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8')!=content:
            raise ValueError('CI workflow differs from its pinned generator. Run python tools/sync_ci.py.')
    else:
        (ROOT/'work').mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir=ROOT/'work') as scratch:
            regenerated=Path(scratch)/'verify.yml';regenerated.write_text(content,encoding='utf-8',newline='\n')
            assert regenerated.read_text(encoding='utf-8')==content
            target.parent.mkdir(parents=True,exist_ok=True)
            target.write_bytes(regenerated.read_bytes())
    print('PASS: CI workflow matches immutable action pins and generator')


if __name__=='__main__': main()
